language: node_js
matrix:
  fast_finish: true
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test
  - yarn build:css:all
  - yarn build:doc:react
  - yarn screenshots --viewport desktop
  - yarn screenshots --no-empty-screenshot-dir --viewport 300x600
  - yarn argos --token $ARGOS_TOKEN --branch $TRAVIS_BRANCH --commit $TRAVIS_COMMIT
deploy:
  - provider: script
    repo: cozy/cozy-ui
    skip-cleanup: true
    script: yarn build:doc:kss && yarn deploy:doc -- --username cozycloud --email contact@cozycloud.cc --repo https://cozy-bot:$GH_TOKEN@github.com/cozy/cozy-ui.git && yarn semantic-release
    on:
      branch: master
